"""Generated by `xime grpc client`. DO NOT EDIT."""
from __future__ import annotations

from pathlib import Path

import grpc.aio

from xime.adapters.grpc.client import SdkRuntime
from ._models import GetPublicKeysRequest, GetPublicKeysResponse, GetSigningKeyRequest, GetSigningKeyResponse

_runtime = SdkRuntime(Path(__file__).with_name("_descriptors.binpb"))


class KeyDistributionServiceClient:
    """Generated client for gRPC service trust.external.key.KeyDistributionService."""

    def __init__(self, channel: grpc.aio.Channel) -> None:
        self._channel = channel

    async def get_public_keys(self, request: GetPublicKeysRequest) -> GetPublicKeysResponse:
        return await _runtime.unary(
            self._channel,
            "/trust.external.key.KeyDistributionService/GetPublicKeys",
            request,
            "GetPublicKeysRequest",
            GetPublicKeysResponse,
            "GetPublicKeysResponse",
        )

    async def get_signing_key(self, request: GetSigningKeyRequest) -> GetSigningKeyResponse:
        return await _runtime.unary(
            self._channel,
            "/trust.external.key.KeyDistributionService/GetSigningKey",
            request,
            "GetSigningKeyRequest",
            GetSigningKeyResponse,
            "GetSigningKeyResponse",
        )
