"""Generated by `xime grpc client`. DO NOT EDIT."""
from __future__ import annotations


from pydantic import BaseModel, Field


class GetPublicKeysRequest(BaseModel):
    verifier_service_id: str


class GetPublicKeysResponse(BaseModel):
    keys: list[PublicKeyDto] = Field(default_factory=list)


class GetSigningKeyRequest(BaseModel):
    signer_service_id: str


class GetSigningKeyResponse(BaseModel):
    keys: list[SigningKeyDto] = Field(default_factory=list)


class PublicKeyDto(BaseModel):
    id: str
    verifier_service_id: str
    algorithm: str
    key_size: int
    public_key: str
    activate_at: int
    expires_at: int


class SigningKeyDto(BaseModel):
    id: str
    signer_service_id: str
    verifier_service_id: str
    algorithm: str
    key_size: int
    private_key: str
    activate_at: int
    expires_at: int


GetPublicKeysRequest.model_rebuild()
GetPublicKeysResponse.model_rebuild()
GetSigningKeyRequest.model_rebuild()
GetSigningKeyResponse.model_rebuild()
PublicKeyDto.model_rebuild()
SigningKeyDto.model_rebuild()
